### ISSUE TITLE
Add an env file

### ISSUE THREAD

**Issue by thisisairo** [Mohsin-mw/Chatvia#1]
### ENV SHOULD CONTAIN VARIABLES FOR:
![Screenshot (77)](https://github.com/Mohsin-mw/Chatvia/assets/122507740/3932c4ad-1439-4eb0-8b00-64804d7cd4a7)
### AFTER CREATING ENV COPY THE DUMMY DATA FROM FIREBASE.REFRENCE.TSX FILE AND PLACE EVERYTHING WITH VARIABLES IN FILE CALLED FIREBASE.TS
![Screenshot (78)](https://github.com/Mohsin-mw/Chatvia/assets/122507740/1ee10d49-bead-4b2e-9172-f8d2620c33a6)

**Comment by nikohoffren** [comment]
Can you assign this issue to me?

**Comment by ducksblock** [comment]
Fixed the issue! #2
